apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mykustomize-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/jinaldesailive/mykustomize.git
    targetRevision: HEAD
    path: solution/overlays/dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: mydev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true